### ISSUE TITLE
Wildfly configClients cannot be null

### ISSUE THREAD

**Issue by AidanDelaney** [pac4j/j2e-pac4j#36]
Hi,
Firstly, thanks for pac4j.  I'm trying to write a tutorial using it through Wildfly but keep running up against a `TechnicalException`.  The exception is as follows:

```
13:38:47,799 ERROR [io.undertow.request] (default task-10) UT005023: Exception handling request to /wildfly-richfaces-braintree-eg/login/facebook: org.pac4j.core.exception.TechnicalException: configClients cannot be null
	at org.pac4j.core.util.CommonHelper.assertTrue(CommonHelper.java:134)
	at org.pac4j.core.util.CommonHelper.assertNotNull(CommonHelper.java:155)
	at org.pac4j.core.engine.DefaultSecurityLogic.perform(DefaultSecurityLogic.java:85)
	at org.pac4j.j2e.filter.SecurityFilter.internalFilter(SecurityFilter.java:71)
	at org.pac4j.j2e.filter.AbstractConfigFilter.doFilter(AbstractConfigFilter.java:81)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

My web.xml contains:

```xml
  <filter>
    <filter-name>FacebookFilter</filter-name>
    <filter-class>org.pac4j.j2e.filter.SecurityFilter</filter-class>
    <init-param>
      <param-name>clients</param-name>
      <param-value>FacebookClient</param-value>
    </init-param>
    <init-param>
      <param-name>authorizers</param-name>
      <param-value>securityHeaders</param-value>
    </init-param>
    <init-param>
      <param-name>matchers</param-name>
      <param-value>excludedPath</param-value>
    </init-param>
  </filter>
  <filter-mapping>
    <filter-name>FacebookFilter</filter-name>
    <url-pattern>/login/facebook/*</url-pattern>
    <dispatcher>REQUEST</dispatcher>
  </filter-mapping>
```
and I've minimised the `DemoConfigFactory` (which I renamed as `ContourConfigFactory`) to only protect a single URL using Facebook auth

```java
package org.ontologyengineering.faces;

import org.pac4j.core.client.Clients;
import org.pac4j.core.client.direct.AnonymousClient;
import org.pac4j.core.config.Config;
import org.pac4j.core.config.ConfigFactory;
import org.pac4j.oauth.client.FacebookClient;

public class ContourConfigFactory implements ConfigFactory {
  public Config build() {
    // these are the pac4j example Facebook tokens
    final FacebookClient facebookClient = new FacebookClient("145278422258960", "be21409ba8f39b5dae2a7de525484da8");
    final Clients clients = new Clients("/callback", facebookClient, new AnonymousClient());

    final Config config = new Config(clients);

    return config;
  }                                              
}

```

Given that I have instantiated a Config for `/login/facebook/*` then is the error I'm getting related to a bug in the interaction with Wildfly?

**Comment by leleuj** [comment]
Are you sure you set the `configFactory` to one of the filters? Like: https://github.com/pac4j/j2e-pac4j-demo/blob/master/src/main/webapp/WEB-INF/web.xml#L91

**Comment by AidanDelaney** [comment]
@leleuj I had not set that.  I omitted it when I was minimising the example.  Thanks a lot.

**Comment by leleuj** [comment]
No problem
